[pytest]
testpaths = tests

markers =
    smoke: Быстрая проверка основного функционала
    regression: Полный набор тестов

addopts =
    -v
    --strict-markers
    --tb=short
    --maxfail=2

filterwarnings =
    ignore::DeprecationWarning
    ignore::ResourceWarning